import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: "1",
    itemName: "Esprit Ruffle Shirt",
    image: "https://preview.colorlib.com/theme/cozastore/images/product-01.jpg.webp",
    description: "A premium quality and stylish T-shirt for men.",
    rating: 4.5,
    reviews: 10,
    size: "L",
    category: "Women",
    oldPrice: 790.99,
    newPrice: 590.99,
    discount: 25,
    isTrending: true,
    inStock: true,
    delivery_time: "2-4 business days",
    fewLeft: true,

  },
  {
    _id: "2",
    itemName: "Only Check Trouser",
    image: "https://preview.colorlib.com/theme/cozastore/images/product-03.jpg.webp",
    description: "A cozy and warm hoodie for kids.",
    rating: 4.7,
    reviews: 8,
    size: "S",
    category: "Men",
    oldPrice: 490.99,
    newPrice: 390.99,
    discount: 20,
    isTrending: true,
    inStock: false,
    delivery_time: "2-4 business days",
    fewLeft: false
  },
  {
    _id: "3",
    itemName: "Herschel supply",
    image: "https://preview.colorlib.com/theme/cozastore/images/product-02.jpg.webp",
    description: "An elegant and fashionable dress for women.",
    rating: 3.2,
    reviews: 5,
    size: "M",
    category: "Women",
    oldPrice: 1290.99,
    newPrice: 990.99,
    discount: 23,
    isTrending: false,
    inStock: true,
    delivery_time: "3-5 business days",
    fewLeft: true,
  },
  
  {
    _id: "4",
    itemName: "Classic Trench Coat",
    image: "https://preview.colorlib.com/theme/cozastore/images/product-04.jpg.webp",
    description: "A stylish and durable jacket for men.",
    rating: 4.2,
    reviews: 12,
    size: "XL",
    category: "Women",
    oldPrice: 1490.99,
    newPrice: 1190.99,
    discount: 20,
    isTrending: false,
    inStock: true,
    delivery_time: "4-6 business days",
    fewLeft: true,
  },
  {
    _id: "5",
    itemName: "Front Pocket Jumper",
    image: "https://preview.colorlib.com/theme/cozastore/images/product-05.jpg.webp",
    description: "A comfortable and trendy pair of jeans for women.",
    rating: 4.8,
    reviews: 15,
    size: "M",
    category: "Women",
    oldPrice: 890.99,
    newPrice: 690.99,
    discount: 22,
    isTrending: true,
    inStock: true,
    delivery_time: "3-5 business days",
    fewLeft: false
  },
  {
    _id: "6",
    itemName: "Vintage Inspired Classic Watch",
    image: "https://preview.colorlib.com/theme/cozastore/images/product-06.jpg.webp",
    description: "A classic and formal shirt for men.",
    rating: 3.9,
    reviews: 6,
    size: "L",
    category: "Accessories",
    oldPrice: 990.99,
    newPrice: 790.99,
    discount: 20,
    isTrending: true,
    inStock: false,
    delivery_time: "2-4 business days",
    fewLeft: false
  },
  {
    _id: "7",
    itemName: "Shirt in Stretch Cotton",
    image: "https://preview.colorlib.com/theme/cozastore/images/product-07.jpg.webp",
    description: "A cozy and stylish sweater for women.",
    rating: 4.1,
    reviews: 9,
    size: "S",
    category: "Women",
    oldPrice: 690.99,
    newPrice: 490.99,
    discount: 29,
    isTrending: false,
    inStock: true,
    delivery_time: "2-4 business days",
    fewLeft: false
  },
  {
    _id: "8",
    itemName: "Pieces Metallic Printed",
    image: "https://preview.colorlib.com/theme/cozastore/images/product-08.jpg.webp",
    description: "Comfortable and breathable shorts for men.",
    rating: 4.6,
    reviews: 11,
    size: "M",
    category: "Women",
    oldPrice: 590.99,
    newPrice: 390.99,
    discount: 33,
    isTrending: true,
    inStock: true,
    delivery_time: "2-4 business days",
    fewLeft: true,
  },
  {
    _id: "9",
    itemName: "Converse All Star Hi Plimsolls shoes",
    image: "https://preview.colorlib.com/theme/cozastore/images/product-09.jpg.webp",
    description: "A stylish and elegant blouse for women.",
    rating: 3.8,
    reviews: 7,
    size: "XL",
    category: "Accessories",
    oldPrice: 490.99,
    newPrice: 390.99,
    discount: 20,
    isTrending: false,
    inStock: false,
    delivery_time: "3-5 business days",
    fewLeft: true,
  },
  {
    _id: "10",
    itemName: "Femme T-Shirt In Stripe",
    image: "https://preview.colorlib.com/theme/cozastore/images/product-10.jpg.webp",
    description: "Stylish and comfortable pants for men.",
    rating: 4.4,
    reviews: 14,
    size: "L",
    category: "Women",
    oldPrice: 790.99,
    newPrice: 590.99,
    discount: 25,
    isTrending: true,
    inStock: true,
    delivery_time: "2-4 business days",
    fewLeft: false
  },
  {
    _id: "11",
    itemName: "Herschel supply",
    image: "https://preview.colorlib.com/theme/cozastore/images/product-11.jpg.webp",
    description: "A fashionable and versatile skirt for women.",
    rating: 4.2,
    reviews: 13,
    size: "M",
    category: "Men",
    oldPrice: 690.99,
    newPrice: 490.99,
    discount: 29,
    isTrending: false,
    inStock: true,
    delivery_time: "3-5 business days",
    fewLeft: false
  },
  {
    _id: "12",
    itemName: "H&M Leather Belt ",
    image: "https://preview.colorlib.com/theme/cozastore/images/product-12.jpg.webp",
    description: "A comfortable and stylish T-shirt for kids.",
    rating: 3.9,
    reviews: 8,
    size: "S",
    category: "Accessories",
    oldPrice: 290.99,
    newPrice: 190.99,
    discount: 33,
    isTrending: true,
    inStock: false,
    delivery_time: "2-4 business days",
    fewLeft: true,
  },
  {
    _id: "13",
    itemName: "BonOrganik",
    image: "https://preview.colorlib.com/theme/cozastore/images/product-14.jpg.webp",
    description: "A warm and trendy hoodie for men.",
    rating: 5,
    reviews: 11,
    size: "L",
    category: "Women",
    oldPrice: 890.99,
    newPrice: 690.99,
    discount: 22,
    isTrending: true,
    inStock: true,
    delivery_time: "2-4 business days",
    fewLeft: false
  },
  {
    _id: "14",
    itemName: "Dennis Lingo Watch",
    image: "https://preview.colorlib.com/theme/cozastore/images/product-15.jpg.webp",
    description: "A stylish and versatile jacket for women.",
    rating: 4.7,
    reviews: 15,
    size: "M",
    category: "Accessories",
    oldPrice: 1490.99,
    newPrice: 1190.99,
    discount: 20,
    isTrending: false,
    inStock: true,
    delivery_time: "3-5 business days",
    fewLeft: false
  },
  {
    _id: "15",
    itemName: "H&M shirt",
    image: "https://preview.colorlib.com/theme/cozastore/images/product-16.jpg.webp",
    description: "A classic and formal shirt for men.",
    rating: 4.1,
    reviews: 9,
    size: "S",
    category: "Women",
    oldPrice: 990.99,
    newPrice: 790.99,
    discount: 20,
    isTrending: true,
    inStock: false,
    delivery_time: "2-4 business days",
    fewLeft: true,
  }
];

